#!/bin/bash
set -e

cat <<'EOF'

This command will run a docker container and maps your current directory to it.
You may provide a port number as an option, default to 8080.

EOF

read -t 30 -p "Press Enter to continue or Ctrl+C to cancel (auto-continue in 30s)..." || true


PORT=${1:-8080}

# Ensure the current directory has markdown files
if [ ! -d "$(pwd)" ]; then
  echo "Error: not a valid directory"
  exit 1
fi

# Run Quartz container
docker run --rm \
  -p ${PORT}:${PORT} \
  -v "$(pwd)":/vault \
  quartz-base \
  ${PORT}
